name: Build C++ (VisionOS)
on:
  workflow_dispatch:
    inputs:
      whisper_cpp_repo:
        description: 'whisper.cpp repo link'
        required: true
        default: 'ggerganov/whisper.cpp'
      whisper_cpp_repo_ref:
        description: 'Tag, branch or commit'
        required: true
        default: 'v1.7.5'
      target_platform:
        description: 'Target platforms'
        required: true
        default: 'all'
jobs:          
  build-ios:
    name: Build for iOS
    if: ${{ contains(fromJson('["ios", "all"]'), github.event.inputs.target_platform) }}
    runs-on: macOS-latest
    steps:
      - name: Clone whisper.unity
        uses: actions/checkout@v3
        with:
          path: whisper-unity
          
      - name: Clone whisper.cpp
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.whisper_cpp_repo }}
          ref: ${{ github.event.inputs.whisper_cpp_repo_ref }}
          path: whisper-cpp
          
      - name: Run build script
        run: |
          cd whisper-unity
          sh build_cpp.sh ${{ github.workspace }}/whisper-cpp/ ios
          
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: ios
          path: ${{ github.workspace }}/whisper-unity/Packages/com.whisper.unity/Plugins/iOS/*.a
          if-no-files-found: error

  build-visionos-metal:
    name: Build for VisionOS Metal (ARM)
    runs-on: macOS-latest
    steps:
      - name: Clone whisper.unity
        uses: actions/checkout@v3
        with:
          path: whisper-unity
  
      - name: Clone whisper.cpp
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.inputs.whisper_cpp_repo }}
          ref: ${{ github.event.inputs.whisper_cpp_repo_ref }}
          path: whisper-cpp
  
      - name: Run build script
        run: |
          cd whisper-unity
          sh build_cpp.sh ../whisper-cpp/ visionos_metal
          cd ${{ github.workspace }}/whisper-cpp/build/
          mv libwhisper.dylib libwhisper_visionos_metal.dylib
  
      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: visionos-metal
          path: |
            ${{ github.workspace }}/whisper-cpp/build/libwhisper_visionos_metal.dylib
            ${{ github.workspace }}/whisper-cpp/build/bin/ggml-metal.metal
          if-no-files-found: error
